### ISSUE TITLE
Arduino Error

### ISSUE THREAD

**Issue by insproad** [witnessmenow/Spotify-NFC-Matrix-Display#3]
Hi my friend, I like so much your project. When I tried that, I fix errors without this

C:\Users\salih\OneDrive\Belgeler\Arduino\libraries\JPEGDEC-master\src/JPEGDEC.h:212:14: error: 'File' has not been declared

     int open(File &file, JPEG_DRAW_CALLBACK *pfnDraw);

              ^

C:\Users\salih\OneDrive\Masaüstü\Spotify-NFC-Matrix-Display-master\Esp32SpotifyMatrixNFC\Esp32SpotifyMatrixNFC.ino: In function 'void drawImageFile(char*)':

Esp32SpotifyMatrixNFC:319:69: error: invalid conversion from 'void (*)(JPEGDRAW*) {aka void (*)(jpeg_draw_tag*)}' to 'int (*)(JPEGDRAW*) {aka int (*)(jpeg_draw_tag*)}' [-fpermissive]

In file included from C:\Users\salih\OneDrive\Masaüstü\Spotify-NFC-Matrix-Display-master\Esp32SpotifyMatrixNFC\Esp32SpotifyMatrixNFC.ino:84:0:

C:\Users\salih\OneDrive\Belgeler\Arduino\libraries\JPEGDEC-master\src/JPEGDEC.h:210:9: note:   initializing argument 6 of 'int JPEGDEC::open(const char*, void* (*)(const char*, int32_t*), void (*)(void*), int32_t (*)(JPEGFILE*, uint8_t*, int32_t), int32_t (*)(JPEGFILE*, int32_t), int (*)(JPEGDRAW*))'

     int open(const char *szFilename, JPEG_OPEN_CALLBACK *pfnOpen, JPEG_CLOSE_CALLBACK *pfnClose, JPEG_READ_CALLBACK *pfnRead, JPEG_SEEK_CALLBACK *pfnSeek, JPEG_DRAW_CALLBACK *pfnDraw);

         ^

exit status 1
invalid conversion from 'void (*)(JPEGDRAW*) {aka void (*)(jpeg_draw_tag*)}' to 'int (*)(JPEGDRAW*) {aka int (*)(jpeg_draw_tag*)}' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by witnessmenow** [comment]
What board do you have selected in the Arduino IDE?

**Comment by insproad** [comment]
> What board do you have selected in the Arduino IDE?

I want to use that with ESP32. So, I choose the ESP32 DEV Module.

**Comment by insproad** [comment]
Have you any suggestion or can you edit for esp32, please I want to use my pixel screen with spotify album covers.

**Comment by witnessmenow** [comment]
This has been fixed, JPEGDRAW added a reference to a File object and the `#define FS_NO_GLOBALS` that was in sketch stopped this from JPEGDRAW library from seeing it.

This define is now removed
